[workspace]
members = [".", "server"]

[package]
name = "Ruzzle"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = { version = "5.7.0" }
renet = "2.0.0"
renet_netcode = "2.0.0"
bincode = "1.3.3"
serde = { version = "1.0.228", features = ["derive"]}
mpsc = "0.2.6"

[patch.crates-io]
raylib = { path = "libs/raylib-rs/raylib" }
